"""online reservations, mellat, sms log, admin

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-25 10:37:09.282318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administration_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hint', sa.String(length=45), server_default='', nullable=False),
    sa.Column('user_agent', sa.String(length=200), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administration_sessions')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_administration_sessions_token_digest'))
    )
    op.create_index('ix_admin_sessions_admin', 'administration_sessions', ['admin_id'], unique=False)
    op.create_table('administration_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'staff')", name=op.f('ck_administration_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administration_users')),
    sa.UniqueConstraint('username', name=op.f('uq_administration_users_username'))
    )
    op.create_table('notifications_sms_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('recipient', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_message_id', sa.String(length=40), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('sent_by', sa.String(length=60), server_default='', nullable=False),
    sa.Column('error', sa.String(length=200), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('transactional', 'bulk')", name=op.f('ck_notifications_sms_messages_kind_valid')),
    sa.CheckConstraint("status IN ('queued', 'sent', 'delivered', 'failed', 'blocked', 'unknown')", name=op.f('ck_notifications_sms_messages_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_sms_messages'))
    )
    op.create_index('ix_sms_created', 'notifications_sms_messages', ['created_at'], unique=False)
    op.create_index('ix_sms_pending', 'notifications_sms_messages', ['created_at'], unique=False, postgresql_where=sa.text("status IN ('queued', 'sent', 'unknown')"))
    op.create_index('ix_sms_provider_id', 'notifications_sms_messages', ['provider_message_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('session_time', sa.Time(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('single_count', sa.Integer(), nullable=False),
    sa.Column('double_count', sa.Integer(), nullable=False),
    sa.Column('amount_irr', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('contact_name', sa.String(length=80), server_default='', nullable=False),
    sa.Column('contact_mobile', sa.String(length=16), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_ref', sa.String(length=64), nullable=True),
    sa.Column('confirmed_late', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('cancel_reason', sa.String(length=300), server_default='', nullable=False),
    sa.CheckConstraint("source <> 'online' OR customer_id IS NOT NULL", name=op.f('ck_reservations_online_has_customer')),
    sa.CheckConstraint("source IN ('online', 'staff')", name=op.f('ck_reservations_source_valid')),
    sa.CheckConstraint("status <> 'held' OR hold_expires_at IS NOT NULL", name=op.f('ck_reservations_hold_has_expiry')),
    sa.CheckConstraint("status IN ('held', 'confirmed', 'attended', 'cancelled', 'expired')", name=op.f('ck_reservations_status_valid')),
    sa.CheckConstraint('amount_irr >= 0', name=op.f('ck_reservations_amount_not_negative')),
    sa.CheckConstraint('single_count + double_count > 0', name=op.f('ck_reservations_at_least_one_kart')),
    sa.CheckConstraint('single_count >= 0 AND double_count >= 0', name=op.f('ck_reservations_counts_not_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('code', name=op.f('uq_reservations_code'))
    )
    op.create_index('ix_reservations_customer', 'reservations', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_reservations_holds', 'reservations', ['hold_expires_at'], unique=False, postgresql_where=sa.text("status = 'held'"))
    op.create_index('ix_reservations_session', 'reservations', ['business_date', 'session_time'], unique=False)
    op.create_table('reservations_settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_reservations_settings_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations_settings'))
    )
    op.add_column('identity_users', sa.Column('full_name', sa.String(length=80), server_default='', nullable=False))
    op.add_column('identity_users', sa.Column('marketing_opt_in', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('payments_attempts', sa.Column('gateway', sa.String(length=16), server_default='', nullable=False))
    op.add_column('payments_attempts', sa.Column('gateway_order_id', sa.BigInteger(), nullable=True))
    op.add_column('payments_attempts', sa.Column('provider_reference', sa.String(length=64), nullable=True))
    op.add_column('payments_attempts', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_payments_order', 'payments_attempts', ['order_ref'], unique=False)
    op.create_unique_constraint(op.f('uq_payments_attempts_gateway_order_id'), 'payments_attempts', ['gateway_order_id'])
    op.create_index('uq_payments_provider_reference', 'payments_attempts', ['gateway', 'provider_reference'], unique=True, postgresql_where=sa.text('provider_reference IS NOT NULL'))
    # ### end Alembic commands ###

    # Numeric order ids for the bank: a sequence never hands out the same value twice.
    op.execute("CREATE SEQUENCE IF NOT EXISTS payments_gateway_order_id_seq START WITH 1000001")
    # New payment states (money waiting to go back, money returned) and: only a paid attempt can be settled.
    op.drop_constraint(op.f("ck_payments_attempts_status_valid"), "payments_attempts", type_="check")
    op.create_check_constraint(
        op.f("ck_payments_attempts_status_valid"),
        "payments_attempts",
        "status IN ('created', 'redirected', 'verifying', 'unknown', 'paid', 'failed', 'expired', "
        "'refund_pending', 'reversed')",
    )
    op.create_check_constraint(
        op.f("ck_payments_attempts_only_paid_is_settled"),
        "payments_attempts",
        "settled_at IS NULL OR status = 'paid'",
    )
    # Payments verified before this migration were captured by their gateway at verification time.
    op.execute("UPDATE payments_attempts SET settled_at = updated_at WHERE status = 'paid'")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_payments_attempts_only_paid_is_settled"), "payments_attempts", type_="check")
    op.drop_constraint(op.f("ck_payments_attempts_status_valid"), "payments_attempts", type_="check")
    op.execute("UPDATE payments_attempts SET status = 'failed' WHERE status IN ('refund_pending', 'reversed')")
    op.create_check_constraint(
        op.f("ck_payments_attempts_status_valid"),
        "payments_attempts",
        "status IN ('created', 'redirected', 'verifying', 'unknown', 'paid', 'failed', 'expired')",
    )
    op.execute("DROP SEQUENCE IF EXISTS payments_gateway_order_id_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payments_provider_reference', table_name='payments_attempts', postgresql_where=sa.text('provider_reference IS NOT NULL'))
    op.drop_constraint(op.f('uq_payments_attempts_gateway_order_id'), 'payments_attempts', type_='unique')
    op.drop_index('ix_payments_order', table_name='payments_attempts')
    op.drop_column('payments_attempts', 'settled_at')
    op.drop_column('payments_attempts', 'provider_reference')
    op.drop_column('payments_attempts', 'gateway_order_id')
    op.drop_column('payments_attempts', 'gateway')
    op.drop_column('identity_users', 'marketing_opt_in')
    op.drop_column('identity_users', 'full_name')
    op.drop_table('reservations_settings')
    op.drop_index('ix_reservations_session', table_name='reservations')
    op.drop_index('ix_reservations_holds', table_name='reservations', postgresql_where=sa.text("status = 'held'"))
    op.drop_index('ix_reservations_customer', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('ix_sms_provider_id', table_name='notifications_sms_messages')
    op.drop_index('ix_sms_pending', table_name='notifications_sms_messages', postgresql_where=sa.text("status IN ('queued', 'sent', 'unknown')"))
    op.drop_index('ix_sms_created', table_name='notifications_sms_messages')
    op.drop_table('notifications_sms_messages')
    op.drop_table('administration_users')
    op.drop_index('ix_admin_sessions_admin', table_name='administration_sessions')
    op.drop_table('administration_sessions')
    # ### end Alembic commands ###
